import io
import sys
import traceback
import pandas as pd
import re
import numpy as np
import json
import matplotlib.pyplot as plt
import base64
from io import BytesIO
from typing import Optional

def run_generated_code(code_str: str) -> str:
    """
    Executes Python code generated by Gemini and captures its output.
    Returns the printed output as a string, or an error message if execution fails.
    """
    global_vars = {
        '__builtins__': __builtins__,
        'pd': pd,
        're': re,
        'np': np,
        'json': json,
        'plt': plt,
        'base64': base64,
        'BytesIO': BytesIO
    }
    local_vars = {}
    stdout_capture = io.StringIO()
    original_stdout = sys.stdout

    try:
        sys.stdout = stdout_capture
        exec(code_str, global_vars, local_vars)
    except Exception as e:
        error_msg = f"❌ Error while executing generated code:\n{traceback.format_exc()}"
        return error_msg
    finally:
        sys.stdout = original_stdout

    return stdout_capture.getvalue().strip()
